spring.application.name=saas-backend

#database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/saas_db
spring.datasource.username=saas_app
spring.datasource.password=23102005

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.user=saas_migrator
spring.flyway.password=23102005

jwt.secret=${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_BASE64_STRING_FOR_LOCAL_DEV_ONLY}
jwt.expiration-ms=3600000